phraseapp:
  access_token: d62438d6857dd67c3f08623edbb03f6bf644c6b248606eefe2afe878e2f9f899
  project_id: dbcdf1946b5e9b1306d2786048a7c5ef
  push:
    sources:
    - file: ./<locale_code>/<tag>.json
      params:
        file_format: simple_json
  pull:
    targets:
    - file: ./<locale_name>/internal.json
      params:
        file_format: simple_json
        tag: internal
        include_empty_translations: true
    - file: ./<locale_name>/general.json
      params:
        file_format: simple_json
        tag: general
        include_empty_translations: true
    - file: ./<locale_name>/test_strings.json
      params:
        file_format: simple_json
        tag: test_strings
        include_empty_translations: true
